#!/bin/sh
# Tyler Grunenwald | github.com/tdgrunenwald

# Adjust background for multi-monitor
feh --bg-tile $HOME/wallpapers/sts-atlantis_3840x1080.jpg

# Adjust lockscreen image for multi-monitor
unlink $HOME/.cache/i3lock/current && ln -s $HOME/.cache/i3lock/3840x1080 $HOME/.cache/i3lock/current
