#!/bin/sh
# Tyler Grunenwald | github.com/tdgrunenwald

# Adjust background for multi-monitor
feh --bg-fill $HOME/wallpapers/sts-atlantis.jpg

# Adjust lockscreen image for multi-monitor
unlink $HOME/.cache/i3lock/current && ln -s $HOME/.cache/i3lock/1920x1080 $HOME/.cache/i3lock/current
