#!/bin/sh
MEM_AVAIL=`cat /proc/meminfo | grep MemAvailable: | awk '{ print $2 }'`
MEM_GB=`echo $MEM_AVAIL | awk '{ printf "%.2GG\n", ($1 / 1024^2) }'`
[ $MEM_AVAIL -lt 2000000 ] && echo "$MEM_GB\n$MEM_GB\n#FF8000"
[ $MEM_AVAIL -lt 1000000 ] && echo "$MEM_GB\n$MEM_GB\n#FF5500"
exit 0
