#!/bin/sh
# Tyler Grunenwald | github.com/tdgrunenwald
# Going to use a runit service to periodically download updates
# This status script just reports if there are any available to install
ICON="ﰵ"
NPKGS=`xbps-install -un | wc -l`	# Count the available updates
[ $NPKGS -eq 0 ] && exit 0			# Exit if no updates available

echo "$ICON $NPKGS"
echo "$ICON $NPKGS"
echo "#FF8000"
