#!/bin/sh
#
# Link config files to home directory and scripts to local scripts directory
#

# change directories to the config directory where this script is located
cd $(dirname $0)

function fileOrDirExists {
	return $([ -d $1 ] || [ -f $1 ])
}

echo Linking homedir configs...

# symlink home dir configs
if [[ -d homedir ]]; then
	for f in homedir/*; do 
		if ! fileOrDirExists ~/.$(basename $f); then
			echo -n $(basename $f)...
			ln -s ~/.config/$f ~/.$(basename $f)
			echo done.
		fi
	done
else
	echo No homedir configs found.
	exit 1
fi

echo Okay. Linking scripts...

# make local scripts dirs if they don't exist already
if ! [[ -d ~/.local/bin ]]; then mkdir -p ~/.local/bin; fi

# symlink scripts to local scripts dir
if [[ -d scripts ]]; then
	for f in scripts/*; do 
		if ! fileOrDirExists ~/.local/bin/$(basename $f); then
			echo -n $(basename $f)...
			ln -s ~/.config/$f ~/.local/bin/$(basename $f)
			echo done.
		fi
	done
else
	echo No scripts found.
	exit 1
fi

echo Done!
exit 0
