" Tyler Grunenwald | github.com/tdgrunenwald
" Set personal vim directory under ~/.config for consistency
set runtimepath=$VIM_HOME,$VIMRUNTIME

if empty(glob('$VIM_HOME/autoload/plug.vim'))
	silent !curl -fLo $VIM_HOME/autoload/plug.vim --create-dirs
		\ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

call plug#begin('$VIM_HOME/vim-plug')
call plug#end()

" Include global tags file in tags file search path
set tags=./tags,./TAGS,\tags,TAGS,$HOME/.config/vim/tags

" Enter the current millenium
set nocompatible

" Access clipboard via the unnamed register
set clipboard=autoselect,unnamedplus

" Formatting
set foldmethod=syntax
set tabstop=4
set shiftwidth=4
set noexpandtab
set autoindent
set cindent
set textwidth=80

" Appearance
"set cursorline
set number
set showcmd
set background=dark

" Search behavior
set hlsearch
set incsearch

" Fuzzy find
set path+=**
set wildmenu

" Editing
set backspace=start,eol

" Syntax and filetype settings
syntax on
filetype plugin indent on

" Fix common typos
nnoremap :Q :q
nnoremap :W :w

" Autocommands
if has("autocmd")
	augroup vimrc
		" Clear autocommands
		autocmd!

		" Add auto commands here...
	augroup END
endif

" Set cursor shape to IBeam in insert mode, underline in replace mode, and block in normal mode.
" Sources http://vim.wikia.com/wiki/Change_cursor_shape_in_different_modes
"         https://vi.stackexchange.com/questions/3379/cursor-shape-under-vim-tmux
"         https://vi.stackexchange.com/questions/7306/vim-normal-and-insert-mode-cursor-not-changing-in-gnu-screen
if &term=="screen" || &term=="screen-256color"
	let &t_SI = "\eP\e[6 q\e\\"
	let &t_SR = "\eP\e[4 q\e\\"
	let &t_EI = "\eP\e[2 q\e\\"
elseif &term=="tmux" || &term=="tmux-256color"
	let &t_SI = "\<esc>Ptmux;\<esc>\e[6 q\<esc>\\"
	let &t_SR = "\<esc>Ptmux;\<esc>\e[4 q\<esc>\\"
	let &t_EI = "\<esc>Ptmux;\<esc>\e[2 q\<esc>\\"
elseif &term!="linux"
	let &t_SI = "\e[6 q"
	let &t_SR = "\e[4 q"
	let &t_EI = "\e[2 q"
endif
