#!/usr/bin/env bash
lock() {
	dm-tool lock
	#betterlockscreen --lock blur
}

case $1 in
	lock)
		lock
		;;
	suspend)
		lock && systemctl suspend
		;;
	hibernate)
		lock && systemctl hibernate
		;;
	reboot)
		systemctl reboot
		;;
	shutdown)
		systemctl poweroff
		;;
	*)
		echo "Usage: $0 [lock|suspend|hibernate|reboot|shutdown]"
		exit 2
esac
exit 0
