#
# ~/.bashrc
#

# source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

stty -ixon                             # disable ctrl-s ctrl-q pause/resume behavior
shopt -s autocd                        # auto cd to directory by just typing its name
shopt -so vi                           # use vi mode
bind -m vi-insert "\C-l":clear-screen  # use Ctrl + L to clear screen in insert mode

export GPG_TTY=$(tty)  # set current tty for gpg-agent

alias grep='grep --color=auto'     # interpret ansi color codes if present
alias less='less -R'               # always interpret ansi color codes
alias ls='ls --color=auto --group-directories-first'
alias pls='ls --color=always -la | less -R'  # paged ls with color
alias vi='vim'
alias v='vim'
alias tmux='tmux -2 -f ~/.config/tmux/config'

# Base16 Shell
BASE16_SHELL="$HOME/code/rice/base16/base16-shell/"
[ -n "$PS1" ] && \
    [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
        eval "$("$BASE16_SHELL/profile_helper.sh")"

# display git branch in PS1
parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}
export PS1="\[\$(tput bold)\]\u@\h \w\$(parse_git_branch) \$ \[\$(tput sgr0)\]"
