#!/usr/bin/env bash
# .bash_profile
#

# load custom aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# set custom environment and startup programs
export LESSOPEN="" # prevent less from auto decrypting GPG encrypted files
export EDITOR="vim"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"

# add location of local binaries and executable scripts to path
PATH="$PATH:$HOME/.local/bin"

# set umask
umask 022

# start X but only on tty1
if [[ "$(tty)" == "/dev/tty1" ]]; then
	startx
	exit 0
fi
