# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions

# make sure terminal is set correctly for colored output
export TERM='st-256color'
export EDITOR='vim'
export XDG_CONFIG_HOME='/home/tyler/.config'

# use vi mode
set -o vi

# display git branch in PS1
parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}
export PS1="\[\$(tput bold)\]\u@\h \w\$(parse_git_branch) \$ \[\$(tput sgr0)\]"
