# 
# xinitrc
#

# merge settings in Xresources
xrdb -merge ~/.Xresources

# set monitor layout correctly
#xrandr --auto --output HDMI-0 --mode 1920x1080 --left-of DVI-I-3 

# set background
~/.fehbg &

# start i3
exec i3
