#!/bin/sh
# 
# xinitrc
#

# merge settings in Xresources
[ -f ~/.Xresources ] && xrdb -I $HOME -merge ~/.Xresources

# set background
[ -f ~/.fehbg ] && ~/.fehbg &

# ctrl+alt+bksp to kill X
setxkbmap -option terminate:ctrl_alt_bksp

# load custom keybindings for non DE specific things e.g. media keys
xbindkeys -f ~/.config/xbindkeys/config

# start i3
exec i3
