#!/bin/sh
# 
# xinitrc
#

# merge settings in Xresources
if [[ -f ~/.Xresources ]]; then
	xrdb -merge ~/.Xresources
fi

# set background
#xsetroot -solid "#002b36"
~/.fehbg &

# ctrl+alt+bksp to kill X
setxkbmap -option terminate:ctrl_alt_bksp

# start i3
exec i3
