#!/bin/sh
MEM_AVAIL=`cat /proc/meminfo | grep MemAvailable: | awk '{ print $2 }'`
MEM_GB=`echo $MEM_AVAIL | awk '{ printf "%.2GG\n", ($1 / 1024^2) }'`

echo "$MEM_GB" # full text
echo "$MEM_GB" # short text
[ $MEM_AVAIL -lt 2000000 ] && COLOR="#FF8000" # text color
[ $MEM_AVAIL -lt 1000000 ] && COLOR="#FF5500" # text color
[ $COLOR != "" ] && echo $COLOR
exit 0
