#!/bin/sh
TEMP=`acpi -t | awk '{ printf "%g\n", $4 | "sort" }' | tail -n 1`

echo "$TEMP℃" # full text
echo "$TEMP℃" # short text
[ $TEMP -gt 70 ] && COLOR="#FF8000" # text color
[ $TEMP -gt 90 ] && COLOR="#FF5500" # text color
[ $COLOR != "" ] && echo $COLOR
exit 0
