#!/bin/sh
# Tyler Grunenwald | github.com/tdgrunenwald
ICON="ﰵ"
ULISTFILE=~/.update-list # TODO remove this after functionality is verified

UCOUNT=`xbps-install -Sun | tee $ULISTFILE | wc -l`

if [ $UCOUNT -gt 0 ]; then
	echo "$UCOUNT $ICON"
	echo "$UCOUNT $ICON"
	echo "#FF8000"
fi
